### PR TITLE
mgr/dashboard_v2: Mark text with the i18n attribute

### PR DESCRIPTION
**Pull request by votdev**
Signed-off-by: Volker Theile <vtheile@suse.com>

### CODE REVIEW

**Review by Exotelis — APPROVED** [review]
One thing we could improve would be to add a description to the attribute. See https://angular.io/guide/i18n#help-the-translator-with-a-description-and-meaning 
This will give the translator at least some kind of context :)

**Review by LenzGr — APPROVED** [review]

**Comment by ricardoasmarques** [comment]
Is there any way to test this PR?

**Comment by votdev** [comment]
@Exotelis Can you comment on @ricardoasmarques question?

**Comment by Exotelis** [comment]
What exactly do you want to test ;)? @ricardoasmarques

**Comment by ricardoasmarques** [comment]
I'm just wondering what is the value of adding translation stuff to the templates without having translation configured on this project, but maybe I'm missing something, so ignore my previous comment.

**Review by ricardoasmarques — APPROVED** [review]

**Comment by Exotelis** [comment]
You are right @ricardoasmarques there is no value. But having the translate attributes is much less value than having at least i18n attributes that can be used in the future :-)

**Comment by LenzGr** [comment]
I think there is merit of adding these attributes to all text elements from the beginning, so enabling translations at some later stage is much easier (as you don't have to wade through the entire code base to identify all translatable strings. So while it does not seem to have any direct value, it's future investment with little overhead at this point.

**Pull request merged**
