### PR TITLE
mgr/dashboard_v2: Create links to perf counters

### PR DESCRIPTION
**Pull request by votdev**
- Display links to the services in the Hosts data table

bildschirmfoto vom 2018-02-16 09-43-37

- Refactor the Performance Counter title

bildschirmfoto vom 2018-02-16 14-34-04

Signed-off-by: Volker Theile <vtheile@suse.com>

### CODE REVIEW

**Comment by votdev** [comment]
Any hints how to get rid of the blank before the comma?

**Review by LenzGr — DISMISSED** [review]

**Comment by ricardoasmarques** [comment]
While testing this PR I've found a lot of links that points to nonexistent pages (e.g. "mds services", "Object Storage"):

peek 2018-02-16 13-04

**Review by ricardoasmarques — CHANGES_REQUESTED** [review]
Some links are not working.

**Comment by ricardoasmarques** [comment]
I also disagree with the breadcrumbs that we have here.

Breadcrumbs are supposed to represent the path that the user followed to reach the current page.

For instance, when I see the following breadcrumb:
  
`  "Performance Counters" > "Monitor" > ...`

I assume that we have a "Performance Counters" menu entry point, and its not the case.

**Comment by votdev** [comment]
@ricardoasmarques Missing MDS performance counter backend has been added

**Comment by tspmelo** [comment]
@ricardoasmarques, @votdev maybe we should remove the breadcrumb from the performance counter page, at least, until we have a proper breadcrumb component (that can keep track from which page the user came from).

**Comment by votdev** [comment]
@ricardoasmarques Because of that the 'Performance Counters' part is not a link because we do not have such an menu item, and i think we should not add such. Any better ideas how to solve this? By the way, this topic should have been discussed in PR #65 which has introduced the Performance Counter page.

**Comment by votdev** [comment]
Breadcumb has been removed.

bildschirmfoto vom 2018-02-16 14-34-04

**Comment by ricardoasmarques** [comment]
@votdev I've not discussed this on https://github.com/openattic/ceph/pull/65 because I agree with what we have on that PR.

Screen from https://github.com/openattic/ceph/pull/65:
screenshot from 2018-02-16 13-38-27

(this means that user clicked on "Cluster->Monitors" and after that he selected "mon.a")

----

@votdev @tspmelo I would prefer to not remove breadcrumbs because it increases the usability a lot, but if it's to much work to do it now, we can do it later on a separate PR.

**Comment by votdev** [comment]
@ricardoasmarques So shall we keep this [commit](https://github.com/openattic/ceph/pull/102/commits/3465499f9b36ca5c8308c4f1f01fe3928af933fd) or shall we drop it and keep the previous solution of this PR?

**Review by ricardoasmarques — DISMISSED** [review]
Breadcrumbs should be added later on a separate PR. Lgtm.

**Review by ricardoasmarques — APPROVED** [review]
LGTM

**Review by tspmelo — APPROVED** [review]

**Review by LenzGr — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
