### PR TITLE
mgr/dashboard_v2: Let the pagination input field look nicer

### PR DESCRIPTION
**Pull request by votdev**
bildschirmfoto vom 2018-02-07 17-51-28

Signed-off-by: Volker Theile <vtheile@suse.com>

### CODE REVIEW

**Review by LenzGr — DISMISSED** [review]

**Comment by tspmelo** [comment]
How about using something like this: http://bootstrap-combobox-test.herokuapp.com/
Maybe we could implement this without adding the plugin...

**Comment by votdev** [comment]
In oA (standalone) we used a dropdown box for the pagination setting. Maybe we could bring that back, but this should be done in a separate PR. Maybe @Devp00l has that already on his ToDo list.

**Review by ricardoasmarques — DISMISSED** [review]
lgtm

**Comment by Devp00l** [comment]
@tspmelo It is possible to do that, but it's not needed anymore, because we aren't doing a GET request on each change of the limit. This way you can set the height that suites you best (in future the value will be stored in the local storage again).

**Review by Devp00l — DISMISSED** [review]

**Review by tspmelo — DISMISSED** [review]
lgtm

**Review by callithea — APPROVED** [review]

**Review by tspmelo — APPROVED** [review]

**Review by Devp00l — APPROVED** [review]

**Pull request merged**
