### PR TITLE
mgr/dashboard_v2: add ceph configuration documentation page

### PR DESCRIPTION
**Pull request by tspmelo**
This PR also introduces filtering for cdTable.

localhost_4200_ fh 2

### CODE REVIEW

**Comment by LenzGr** [comment]
How about calling it **Configuration Reference** or **Configuration Documentation** instead of **Configuration** - in the end, there's nothing to configure here (and one can't even see the actual config values atm).

**Comment by sebastian-philipp** [comment]
Would it make sense to call this PR **"mgr/dashboard_v2: add ceph configuration documentation page"**?

**Comment by tspmelo** [comment]
Just updated the PR.
we are now using a basic html table for displaying all the configurations and I have change the name of the page and PR to "Configuration Documentation"

192 168 1 136_4200_ fhd 6

**Review by ricardoasmarques — APPROVED** [review]
lgtm

**Pull request merged**
