### PR TITLE
Support for unit testing

### PR DESCRIPTION
**Pull request by rjfd**
This PR introduces the necessary infrastructure to run unit tests for openattic mgr plugin.

### CODE REVIEW

**Review by sebastian-philipp — APPROVED** [review]

**Comment by sebastian-philipp** [comment]
would it make sense to exclude this from the initial PR?

**Review by LenzGr — APPROVED** [review]
lgtm, thanks!

**Comment by LenzGr** [comment]
@sebastian-philipp I'd be in favor of including it. Having a test framework in place is necessary groundwork.

**Comment by sebastian-philipp** [comment]
yes, but the groundwork will be added later and should not be part of this PR imo.

**Pull request merged**
