### PR TITLE
[WIP, DNM] mgr/dashboard_v2: Imported RBD Nodb model

### PR DESCRIPTION
**Pull request by sebastian-philipp**
TODOs:

* I'm open to suggestions on how to improve this `import rbd` drama.
* I'm also open to suggestions on how to improve this `PYTHONPATH / LD_LIBRARY_PATH` drama.
* We can no longer execute all tests in a Python 2 and Python 3 environment.
* ~Haven't executed it within the manager yet.~
* Depends on `CephPool` by @s0nea 
* Haven't found a solution for hanging requests. Thus, this bug is back now.
* `Module.rados` will be gone as soon as we are on top of ceph/ceph:master again. 

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

### CODE REVIEW

**Comment by rjfd** [comment]
depends on #55

**Comment by rjfd** [comment]
@sebastian-philipp could you explain in more detail what is the problem with `import rbd`?
Is this a problem only in the test environment, or it happens when running through the ceph-mgr?

**Comment by sebastian-philipp** [comment]
I need a reliable way to use a recent `rbd` Python module with a compatible `librbd` library. I can only think of `/ceph/build/lib/cython_modules/lib.2/rbd.so` and `/ceph/build/lib/librbd.so`. 

But this has some downsides:

1. `rbd.so` is either built for Python 2 or for Python 3. Thus either we're skipping the unit tests for Python 2 or for Python 3. And we have to cope with `ImportErrors` when importing `rbd`.
2. As both libraries are not in any standard search path, we have to set `PYTHONPATH` and `LD_LIBRARY_PATH` for all unit tests (including pylint!). This is also true when running within mgr, but this is done by `vstart`. 
3. The controller is automatically loaded by `module.py`, therefore the controller needs to also cope with an import error.

**Comment by rjfd** [comment]
@sebastian-philipp when you compile ceph with support for python3, it will create a different library directory for holding the python3 libraries.
To compile ceph with support for python3 just add the `-DWITH_PYTHON3=on` to cmake command.

Then we can have different `PYTHONPATH` env vars for the python2 and 3 tests:

* python2: `PYTHONPATH = {toxinidir}/../../../../build/lib/cython_modules/lib.2:../../`
* python3: `PYTHONPATH = {toxinidir}/../../../../build/lib/cython_modules/lib.3:../../`

**Comment by rjfd** [comment]
@sebastian-philipp  regarding:
> https://github.com/openattic/ceph/blob/wip-mgr-dashboard_v2/src/pybind/mgr/dashboard/remote_view_cache.py

Perhaps we could implement something similar to this: https://github.com/openattic/ceph/blob/wip-mgr-dashboard_v2/src/pybind/mgr/dashboard/remote_view_cache.py

**Comment by sebastian-philipp** [comment]
regarding `remote_view_cache`: This is very similar to https://bitbucket.org/openattic/openattic/src/660f1bb4979c14ed8023853e39b09362ef5cbb03/backend/utilities.py?at=master&fileviewer=file-view-default#utilities.py-136

**Comment by sebastian-philipp** [comment]
Regarding `build/lib/cython_modules/lib.{2,3}`: This still doesn't fix the problem that we either have a Python 2 or a Python 3 version of `rbd`

**Comment by rjfd** [comment]
@sebastian-philipp 
> This still doesn't fix the problem that we either have a Python 2 or a Python 3 version of rbd

I don't understand why it does not fix. When running python 2 you use one path, when running python 3 use the other path.

What am I missing here?

**Comment by sebastian-philipp** [comment]
Just a small misunderstanding. `-DWITH_PYTHON3=on` means Python 2 and Python 3 instead of just Python 3

**Comment by jecluis** [comment]
Tangential question to the PR: when the commit states "Imported RBD Nodb model", what does the "import" part actually refers to?

**Comment by sebastian-philipp** [comment]
@jecluis This model was imported from https://bitbucket.org/openattic/openattic/src/660f1bb4979c14ed8023853e39b09362ef5cbb03/backend/ceph/models.py?at=master&fileviewer=file-view-default#models.py-797:1004

**Comment by jecluis** [comment]
> @jecluis This model was imported from https://bitbucket.org/openattic/openattic/src/660f1bb4979c14ed8023853e39b09362ef5cbb03/backend/ceph/models.py?at=master&fileviewer=file-view-default#models.py-797:1004

Unless you specify that, which I think would be moot tbh, I think what you actually mean is that you are **adding** code to Ceph. All this "import" stuff from some unspecified place is not relevant information given the current context of these commits; also, it's confusing (because, *"where is this being imported to or from?"*).

I would be ever more grateful if now, and in the future, you and everyone else would refrain from referring to **new** patches as *imports*. :)

Also, this PR needs a rebase.

**Comment by jecluis** [comment]
@sebastian-philipp is there a reason this PR needs to be merged before the initial PR to ceph/master, or can we tag this to be revisited only after?

**Comment by jecluis** [comment]
As per our chat on IRC, this PR depends on https://github.com/openattic/ceph/pull/55 and should be merged at the same time.

**Comment by sebastian-philipp** [comment]
For now, there won't be any NoDB in mgr/dashboard_v2.

**Pull request closed without merging**
