### PR TITLE
mgr/dashboard_v2: add sparkline component

### PR DESCRIPTION
**Pull request by tspmelo**
Signed-off-by: Tiago Melo <tmelo@suse.com>

ATM you can only change the size and update the data of this components.
Do you think we need more customization? Or just define 1 style and use that in every page?

image

### CODE REVIEW

**Comment by ricardoasmarques** [comment]
@tspmelo IMO we don't need more customization, for now.

I'm in favor of defining one style that will be used everywhere.

**Review by LenzGr — APPROVED** [review]

**Comment by tspmelo** [comment]
current color schema:
image

**Review by callithea — APPROVED** [review]

**Review by jecluis — CHANGES_REQUESTED** [review]
can you please elaborate on the commit message what this is for, or why do we need it? Maybe I'm mistaken, but it looks like this is not being used anywhere, and a bit of background on why it is needed would be nice.

**Comment by tspmelo** [comment]
This component will be include in  PR #65.

**Pull request closed without merging**
